# Generated by Django 2.2.9 on 2020-01-20 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_pri', models.IntegerField(default=0)),
                ('task_name', models.CharField(default='', max_length=50)),
                ('task_time', models.CharField(default='00:00', max_length=50)),
                ('task_rgst', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
