# Generated by Django 2.2.9 on 2020-01-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_pri',
            new_name='pri',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_rgst',
            new_name='rgst',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_time',
            new_name='time',
        ),
    ]
