# Generated by Django 2.2.9 on 2020-01-21 05:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0003_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='rgst',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='summary',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='tasker.Task', verbose_name='task'),
        ),
    ]
