# Generated by Django 2.2.9 on 2020-01-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0004_auto_20200121_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
