# Generated by Django 2.2.9 on 2020-01-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0005_summary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.CharField(default='00:00', max_length=100),
        ),
    ]
