# Generated by Django 2.2.9 on 2020-01-21 20:08

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0007_auto_20200122_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='updt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=markdownx.models.MarkdownxField(help_text='Markdown形式で書いてください。', verbose_name=''),
        ),
    ]
