# Generated by Django 2.2.9 on 2020-01-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0008_auto_20200122_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updt',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
