# Generated by Django 2.2.9 on 2020-04-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0010_auto_20200409_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='esa_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
